routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KeluhanController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('User.Home');
});

Route::get('/loginUser', function () {
    return view('auth.loginGoogle');
});

Route::get('/loginUser', [App\Http\Controllers\GoogleLoginController::class, 'login'])->name('google.login');

Route::get('/tambah', function () {
    return view('keluhan.tambah');
});

Route::resource('/keluhan',
\App\Http\Controllers\KeluhanController::class);

Route::resource('/Dashboard', '\App\Http\Controllers\DashboardController')
    ->middleware('auth', 'restrict.user:null'); // Change 'null' to the role allowed to access

Route::resource('/DataPasien', '\App\Http\Controllers\DataPasienController')
    ->middleware('auth', 'restrict.user:null');

Route::resource('/emergency', '\App\Http\Controllers\EmergencyController')
    ->middleware('auth', 'restrict.user:null');


Route::get('/google/redirect', [App\Http\Controllers\GoogleLoginController::class, 'redirectToGoogle'])->name('google.redirect');
Route::get('/google/callback', [App\Http\Controllers\GoogleLoginController::class, 'handleGoogleCallback'])->name('google.callback');

Route::resource('/poli',
\App\Http\Controllers\PoliController::class)->middleware('auth');


Route::resource('/laporan',
\App\Http\Controllers\LaporanController::class)->middleware('auth');

Route::resource('/pendaftaran',
\App\Http\Controllers\PemilikHewanController::class);

Route::resource('/HewanPulang',
\App\Http\Controllers\RiwayatHewanController::class);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::resource('/coba',
\App\Http\Controllers\cobaController::class);


Route::resource('/ViewAdmin',
\App\Http\Controllers\AdminController::class);

Route::resource('/Home',
\App\Http\Controllers\HomeController::class);

Route::delete('/keluhan/{id_keluhan}', 'KeluhanController@hapusKeluhan')->name('keluhan.hapusKeluhan');

resources/views/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>@yield('title', $title)</title>
</head>

<body>
    <div class="container">
        @yield('content')
    </div>
</body>

</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en" class="scroll-smooth group" data-sidebar="brand" dir="ltr">
    <head>
        <meta charset="utf-8" />
        <title>Login Sistem Pengajuan Keluhan Pada Klinik Hewan</title>
        <meta  name="viewport"  content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta  content="Tailwind Multipurpose Admin & Dashboard Template"  name="description"/>
        <meta content="" name="Mannatthemes" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico" />
        
        <!-- Css -->
        <!-- Main Css -->
        <link rel="stylesheet" href="{{asset('AdminLTE')}}/dist/assets/libs/icofont/icofont.min.css">
        <link href="{{asset('AdminLTE')}}/dist/assets/libs/flatpickr/flatpickr.min.css" type="text/css" rel="stylesheet">
        <link rel="stylesheet" href="{{asset('AdminLTE')}}/dist/assets/css/tailwind.min.css">

    </head>
    
    <body data-layout-mode="light"  data-sidebar-size="default" data-theme-layout="vertical" class="bg-[#EEF0FC] dark:bg-gray-900">
    
    <div class="relative flex flex-col justify-center min-h-screen overflow-hidden">
        <div class="w-full  m-auto bg-white dark:bg-slate-800/60 rounded shadow-lg ring-2 ring-slate-300/50 dark:ring-slate-700/50 lg:max-w-md">
            <div class="text-center p-6 bg-slate-900 rounded-t">
                <a href="index.html"><img src="{{asset('AdminLTE')}}/dist/assets/images/logo-sm.png" alt="" class="w-14 h-14 mx-auto mb-2"></a>
                <h3 class="font-semibold text-white text-xl mb-1">SISTEM PENGAJUAN KELUHAN PADA KLINIK HEWAN</h3>
                <p class="text-xs text-slate-400">Sign in to continue.</p>
            </div>

            <form action="{{ route('Dashboard.index') }}" method="GET" class="p-6">
                <div>
                    <label for="username" class="font-medium text-sm text-slate-600 dark:text-slate-400">Username</label>
                    <input type="username" id="username" class="form-input w-full rounded-md mt-1 border border-slate-300/60 dark:border-slate-700 dark:text-slate-300 bg-transparent px-3 py-2 focus:outline-none focus:ring-0 placeholder:text-slate-400/70 placeholder:font-normal placeholder:text-sm hover:border-slate-400 focus:border-primary-500 dark:focus:border-primary-500  dark:hover:border-slate-700" placeholder="Your Username" required>
                </div>
                <div class="mt-4">
                    <label for="password" class="font-medium text-sm text-slate-600 dark:text-slate-400">Your password</label>
                    <input type="password" id="password" class="form-input w-full rounded-md mt-1 border border-slate-300/60 dark:border-slate-700 dark:text-slate-300 bg-transparent px-3 py-2 focus:outline-none focus:ring-0 placeholder:text-slate-400/70 placeholder:font-normal placeholder:text-sm hover:border-slate-400 focus:border-primary-500 dark:focus:border-primary-500  dark:hover:border-slate-700" placeholder="Password"  required>
                </div>
                <div class="block mt-3">
                    <label class="custom-label block dark:text-slate-300">
                        <div class="bg-white dark:bg-slate-700  border border-slate-200 dark:border-slate-600 rounded w-4 h-4  inline-block leading-4 text-center -mb-[3px]">
                          <input type="checkbox" class="hidden">
                          <i class="fas fa-check hidden text-xs text-slate-700 dark:text-slate-200"></i>
                        </div>
                        Remember me
                    </label>
                </div>                    
                <div class="mt-4">
                    <button
                        class="w-full px-2 py-2 tracking-wide text-white transition-colors duration-200 transform bg-brand-500 rounded hover:bg-brand-600 focus:outline-none focus:bg-brand-600">
                        Login
                    </button>
                    
                </div>
            </form>
            <a href="{{ route('Home.index') }}" class="block mt-2">
                        <button
                            class="w-full px-2 py-2 tracking-wide text-white transition-colors duration-200 transform bg-brand-500 rounded hover:bg-brand-600 focus:outline-none focus:bg-brand-600">
                            Home
                        </button>
            <p class="mb-5 text-sm font-medium text-center text-slate-500"> Don't have an account? <a href="{{ route('register') }}"
                class="font-medium text-brand-500 hover:underline">Sign up</a>
            </p>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        @if (session()->has('success'))
            toastr.success('{{ session('success') }}', 'BERHASIL!');
        @elseif (session()->has('error'))
            toastr.error('{{ session('error') }}', 'GAGAL!');
        @endif
    </script>
</body>

</html>

resources/views/register.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Data Admin</title>
    <!-- Include Tailwind CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body class="bg-gray-300">
    <div class="container mx-auto mt-5 mb-5 lg:w-1/2 xl:w-1/3 mx-auto">
        @extends('app')

        @section('content')
        <div class="w-full  m-auto bg-white dark:bg-slate-800/60 rounded shadow-lg ring-2 ring-slate-300/50 dark:ring-slate-700/50 lg:max-w-md">
            <div class="text-center p-6 bg-slate-900 rounded-t">
                <h2 class="text-2xl font-bold text-gray-800">Register Admin</h2>
            </div>

            @if($errors->any())
                @foreach($errors->all() as $err)
                    <p class="alert alert-danger">{{ $err }}</p>
                @endforeach
            @endif

            <form action="{{ route('register.action') }}" method="POST">
                @csrf
                <div class="mb-4">
                    <label for="Name" class="block text-gray-700 text-sm font-bold mb-2">Name</label>
                    <input class="w-full border border-gray-300 px-3 py-2 rounded focus:outline-none focus:border-indigo-500" type="text" name="name" value="{{ old('name') }}" />
                </div>
                <div class="mb-3">
                    <label class="block text-gray-700 text-sm font-bold mb-2">Username <span class="text-danger">*</span></label>
                    <input class="w-full border border-gray-300 px-3 py-2 rounded focus:outline-none focus:border-indigo-500" type="username" name="username" value="{{ old('username') }}" />
                </div>
                <div class="mb-3">
                    <label class="block text-gray-700 text-sm font-bold mb-2">Password <span class="text-danger">*</span></label>
                    <input class="w-full border border-gray-300 px-3 py-2 rounded focus:outline-none focus:border-indigo-500" type="password" name="password" />
                </div>
                <div class="mb-3">
                    <label class="block text-gray-700 text-sm font-bold mb-2">Password Confirmation <span class="text-danger">*</span></label>
                    <input class="w-full border border-gray-300 px-3 py-2 rounded focus:outline-none focus:border-indigo-500" type="password" name="password_confirm" />
                </div>
                <div class="mb-3 text-center">
                    <button class="bg-blue-500 text-white px-4 py-2 rounded">Register</button>
                </div>
            </form>

            <p class="mb-5 text-sm font-medium text-center text-gray-700">
                Already have an account? <a href="{{ route('login') }}" class="text-blue-500 hover:underline">Log in</a>
            </p>
        </div>
        @endsection
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('description');
    </script>
</body>

</html>