routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KeluhanController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('User.Home');
});

Route::get('/loginUser', function () {
    return view('auth.loginGoogle');
});

Route::get('/loginUser', [App\Http\Controllers\GoogleLoginController::class, 'login'])->name('google.login');

Route::get('/tambah', function () {
    return view('keluhan.tambah');
});

Route::resource('/keluhan',
\App\Http\Controllers\KeluhanController::class);

Route::resource('/Dashboard', '\App\Http\Controllers\DashboardController')
    ->middleware('auth', 'restrict.user:null'); // Change 'null' to the role allowed to access

Route::resource('/DataPasien', '\App\Http\Controllers\DataPasienController')
    ->middleware('auth', 'restrict.user:null');

Route::resource('/emergency', '\App\Http\Controllers\EmergencyController')
    ->middleware('auth', 'restrict.user:null');


Route::get('/google/redirect', [App\Http\Controllers\GoogleLoginController::class, 'redirectToGoogle'])->name('google.redirect');
Route::get('/google/callback', [App\Http\Controllers\GoogleLoginController::class, 'handleGoogleCallback'])->name('google.callback');

Route::resource('/poli',
\App\Http\Controllers\PoliController::class)->middleware('auth');


Route::resource('/laporan',
\App\Http\Controllers\LaporanController::class)->middleware('auth');

Route::resource('/pendaftaran',
\App\Http\Controllers\PemilikHewanController::class);

Route::resource('/HewanPulang',
\App\Http\Controllers\RiwayatHewanController::class);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::resource('/coba',
\App\Http\Controllers\cobaController::class);


Route::resource('/ViewAdmin',
\App\Http\Controllers\AdminController::class);

Route::resource('/Home',
\App\Http\Controllers\HomeController::class);

Route::delete('/keluhan/{id_keluhan}', 'KeluhanController@hapusKeluhan')->name('keluhan.hapusKeluhan');

app/Models/keluhan.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Keluhan extends Model
{
    protected $table = 'keluhan';
    protected $primaryKey = 'id_keluhan';
   
    public function pendaftaran() 
    {
        return $this->belongsTo(Pendaftaran::class, 'id_daftar', 'id_daftar');
    }

    protected static function booted()
    {
        // Event deleting pada model Keluhan
        static::deleting(function ($keluhan) {
            // Menghapus data dari tabel Pendaftaran yang memiliki foreign key yang sama dengan id_daftar pada Keluhan yang dihapus
            Pendaftaran::where('id_daftar', $keluhan->id_daftar)->delete();
        });
    }


    public function poli()
    {
        return $this->hasMany(Poli::class, 'id_keluhan');
    }

    public function emergency()
    {
        return $this->hasMany(emergency::class, 'id_keluhan');
    }
}

app/Http/Controllers/KeluhanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\keluhan;
use App\Models\pendaftaran;
use App\Models\poli;
use App\Models\emergency;
use App\Models\laporan;

use DB;


class KeluhanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $keluhan = Keluhan::with('pendaftaran')
        ->orderByDesc('id_keluhan')->whereNull('status')
        ->get();

    return view('keluhan.utama', ['keluhan' => $keluhan]);
    }
   


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store( Request $request)
{
    $this->validate($request, [
        'desc_keluhan',
        'tanggal_keluhan',
        'id_daftar'  
    ]);

    $id_daftar = $request->input('id_daftar');

    $id_keluhan = DB::table('keluhan')->insertGetId([
        'desc_keluhan' => $request->input('desc_keluhan'),
        'tanggal_keluhan' => $request->input('tanggal_keluhan'),
        'id_daftar' => $id_daftar,
    ]);

    $latestKeluhan = DB::table('keluhan')
        ->where('id_keluhan', $id_keluhan)
        ->orderByDesc('id_keluhan')
        ->first();
   
    return redirect()->route('keluhan.index')->with(['success'=> 'Data Berhasil Disimpan!']);
}


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
        public function destroy($id)
        {
            DB::table('keluhan')->where('id_keluhan', $id)->Delete();
            return redirect()->route('keluhan.index')->with(['success' => 'Data Behasil Di Hapus']);
        }
    
}

resources/views/keluhan/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Data Keluhan - Penerimaan Mahasiswa Baru</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('keluhan.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label class="font-weight-bold">Keluhan</label>
                                <input type="varchar2" class="form-control @error('desc_keluhan') is-invalid @enderror" name="desc_keluhan" placeholder="Masukkan Keluhan Hewan Anda">
                                @error('desc_keluhan')
                                    <div class="alert alert-danger mt-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Tanggal Keluhan</label>
                                <input type="date" class="form-control @error('tanggal_keluhan') is-invalid @enderror" name="tanggal_keluhan">
                                @error('tanggal_keluhan')
                                    <div class="alert alert-danger mt-2">{{ $message }}</div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-md btn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-md btn-warning">RESET</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>